### ISSUE TITLE
LUA error after patch 1.13.3

### ISSUE THREAD

**Issue by srbrunner** [aabasharain/SimpleRecallTotems#1]
I love this addon, but it stopped working after the 1.13.3 patch.  Here is the error I get.  I have turned all addons off accept SRT.  I hope there is a fix.

Message: Interface\FrameXML\SecureTemplates.lua:460: attempt to call global 'DestroyTotem' (a nil value)
Time: Wed Dec 11 22:04:46 2019
Count: 4
Stack: Interface\FrameXML\SecureTemplates.lua:460: attempt to call global 'DestroyTotem' (a nil value)
Interface\FrameXML\SecureTemplates.lua:460: in function `handler'
Interface\FrameXML\SecureTemplates.lua:616: in function <Interface\FrameXML\SecureTemplates.lua:564>
[C]: in function `Click'
Interface\FrameXML\ChatFrame.lua:1583: in function `?'
Interface\FrameXML\ChatFrame.lua:4646: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4327: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:2754: in function <Interface\FrameXML\ChatFrame.lua:2747>
[C]: in function `RunMacroText'
Interface\FrameXML\SecureTemplates.lua:424: in function `handler'
Interface\FrameXML\SecureTemplates.lua:616: in function <Interface\FrameXML\SecureTemplates.lua:564>

Locals: self = SRT_totem4 {
 0 = <userdata>
}
unit = nil
button = "LeftButton"
(*temporary) = nil
(*temporary) = 4
(*temporary) = "attempt to call global 'DestroyTotem' (a nil value)"

**Comment by aabasharain** [comment]
Quite a few things got changed with this last patch, including what I (and others) used to be able to destroy totems. As far as I know there isn't a way to destroy totems besides this method, but I need to look into the API more and see if there is another workaround.
